name: Publish plugin

on:
  release:
    types: [published]

env:
  PLUGIN_NAME: logseq-plugin-url-to-markdown

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Package plugin
        run: |
          mkdir ${{ env.PLUGIN_NAME }}
          cp README.md package.json manifest.json ${{ env.PLUGIN_NAME }}
          cp assets/favicon.svg ${{ env.PLUGIN_NAME }}/favicon.svg
          mv dist ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          ls -la

      - name: Upload release assets
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "./${{ env.PLUGIN_NAME }}.zip,./package.json"
          artifactContentType: "application/zip,application/json"
          token: ${{ secrets.GITHUB_TOKEN }}
